# Generated by Django 4.2.7 on 2024-03-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='stock',
            field=models.IntegerField(default=True),
        ),
    ]
