# Generated by Django 4.2.7 on 2024-03-14 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_part_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
